// <auto-generated />
using System;
using HR_Server.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HR_Server.Migrations
{
    [DbContext(typeof(HrDbContext))]
    partial class HrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HR_Server.Model.Person", b =>
                {
                    b.Property<long>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("DiatomEnterviewees")
                        .HasMaxLength(250);

                    b.Property<string>("Email")
                        .HasMaxLength(150);

                    b.Property<string>("Experience")
                        .HasMaxLength(1000);

                    b.Property<DateTime>("InterviewDate")
                        .HasColumnType("smalldatetime");

                    b.Property<bool>("IsCvUploaded")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(150);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000);

                    b.Property<string>("Other")
                        .HasMaxLength(150);

                    b.Property<string>("Position")
                        .HasMaxLength(150);

                    b.Property<decimal>("Rate")
                        .HasColumnType("money");

                    b.Property<string>("Status")
                        .HasMaxLength(150);

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
